# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwin(object):
    def setupUi(self, mainwin):
        mainwin.setObjectName("mainwin")
        mainwin.resize(800, 598)
        self.centralwidget = QtWidgets.QWidget(mainwin)
        self.centralwidget.setObjectName("centralwidget")
        self.name_lb = QtWidgets.QLabel(self.centralwidget)
        self.name_lb.setGeometry(QtCore.QRect(720, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_lb.setFont(font)
        self.name_lb.setObjectName("name_lb")
        self.get_btn = QtWidgets.QPushButton(self.centralwidget)
        self.get_btn.setGeometry(QtCore.QRect(230, 400, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.get_btn.setFont(font)
        self.get_btn.setObjectName("get_lb")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 240, 431, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.papka_btn = QtWidgets.QPushButton(self.centralwidget)
        self.papka_btn.setGeometry(QtCore.QRect(250, 470, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.papka_btn.setFont(font)
        self.papka_btn.setObjectName("papka_lb")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 220, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.result_lb = QtWidgets.QLabel(self.centralwidget)
        self.result_lb.setGeometry(QtCore.QRect(140, 370, 491, 20))
        self.result_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.result_lb.setObjectName("result_lb")
        mainwin.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainwin)
        QtCore.QMetaObject.connectSlotsByName(mainwin)

    def retranslateUi(self, mainwin):
        _translate = QtCore.QCoreApplication.translate
        mainwin.setWindowTitle(_translate("mainwin", "Hasker."))
        self.name_lb.setText(_translate("mainwin", "Hasker."))
        self.get_btn.setText(_translate("mainwin", "Отримати html код"))
        self.papka_btn.setText(_translate("mainwin", "обрати папку"))
        self.label.setText(_translate("mainwin", "Посилання на сайт:"))
        self.result_lb.setText(_translate("mainwin", "Ура!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainwin = QtWidgets.QMainWindow()
    ui = Ui_mainwin()
    ui.setupUi(mainwin)
    mainwin.show()
    sys.exit(app.exec_())
